import type { Metadata } from "next"
import "./globals.css"
import { FloatingAIChat } from "@/components/ai/floating-ai-chat"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        {children}
        <FloatingAIChat />
      </body>
    </html>
  );
}
